-- Script para inserir dados de teste na tabela fiscal_appointments
-- Execute este script no Supabase SQL Editor

-- IMPORTANTE: Substitua 'SEU_STUDENT_ID_AQUI' pelo ID real do estudante logado
-- Você pode pegar o ID do estudante fazendo login e verificando o token JWT ou consultando a tabela students

-- Exemplo 1: Atendimento Confirmado - Declaração de IRPF
INSERT INTO public.fiscal_appointments (
  protocol,
  service_type,
  service_title,
  service_category,
  client_name,
  client_email,
  client_phone,
  client_cpf,
  address_street,
  address_number,
  address_complement,
  address_neighborhood,
  address_city,
  address_state,
  address_zipcode,
  urgency_level,
  preferred_date,
  preferred_time,
  preferred_period,
  status,
  client_notes,
  internal_notes,
  service_details,
  assigned_student_id,
  created_at,
  updated_at,
  confirmed_at
) VALUES (
  'FAP-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-001',
  'declaracao-irpf',
  'Declaração de Imposto de Renda Pessoa Física 2024',
  'IRPF',
  'Maria da Silva Santos',
  'maria.santos@email.com',
  '(11) 98765-4321',
  '123.456.789-00',
  'Rua das Flores',
  '123',
  'Apto 45',
  'Centro',
  'São Paulo',
  'SP',
  '01234-567',
  'NORMAL',
  CURRENT_DATE + INTERVAL '3 days',
  '10:00',
  'MANHA',
  'CONFIRMADO',
  'Primeira vez declarando IR, preciso de ajuda com todos os passos. Tenho renda de trabalho CLT e alguns investimentos.',
  NULL,
  '{
    "income_sources": ["CLT", "Investimentos"],
    "has_dependents": true,
    "number_of_dependents": 2,
    "first_time_declaring": true
  }'::jsonb,
  'SEU_STUDENT_ID_AQUI',
  NOW(),
  NOW(),
  NOW()
);

-- Exemplo 2: Atendimento Pendente - Orientação MEI
INSERT INTO public.fiscal_appointments (
  protocol,
  service_type,
  service_title,
  service_category,
  client_name,
  client_email,
  client_phone,
  client_cpf,
  address_street,
  address_number,
  address_neighborhood,
  address_city,
  address_state,
  address_zipcode,
  urgency_level,
  preferred_date,
  preferred_time,
  preferred_period,
  status,
  client_notes,
  service_details,
  assigned_student_id,
  created_at,
  updated_at
) VALUES (
  'FAP-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-002',
  'orientacao-mei',
  'Orientação sobre abertura de MEI',
  'MEI',
  'João Carlos Oliveira',
  'joao.oliveira@email.com',
  '(11) 97654-3210',
  '987.654.321-00',
  'Av. Paulista',
  '1500',
  'Bela Vista',
  'São Paulo',
  'SP',
  '01310-100',
  'ALTA',
  CURRENT_DATE + INTERVAL '2 days',
  '14:00',
  'TARDE',
  'PENDENTE',
  'Quero abrir MEI para trabalhar como designer freelancer. Tenho dúvidas sobre tributação e obrigações mensais.',
  '{
    "business_type": "Designer Gráfico",
    "estimated_monthly_revenue": 3000,
    "has_employees": false
  }'::jsonb,
  'SEU_STUDENT_ID_AQUI',
  NOW(),
  NOW()
);

-- Exemplo 3: Atendimento Em Andamento - Consulta Tributária
INSERT INTO public.fiscal_appointments (
  protocol,
  service_type,
  service_title,
  service_category,
  client_name,
  client_email,
  client_phone,
  client_cpf,
  address_street,
  address_number,
  address_complement,
  address_neighborhood,
  address_city,
  address_state,
  address_zipcode,
  urgency_level,
  preferred_date,
  preferred_time,
  preferred_period,
  status,
  client_notes,
  internal_notes,
  service_details,
  assigned_student_id,
  created_at,
  updated_at,
  confirmed_at,
  scheduled_at
) VALUES (
  'FAP-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-003',
  'consulta-tributaria',
  'Consulta sobre tributação de aluguel',
  'Tributação',
  'Ana Paula Costa',
  'ana.costa@email.com',
  '(11) 96543-2109',
  '456.789.123-00',
  'Rua Augusta',
  '789',
  'Sala 12',
  'Consolação',
  'São Paulo',
  'SP',
  '01305-000',
  'NORMAL',
  CURRENT_DATE,
  '09:00',
  'MANHA',
  'EM_ANDAMENTO',
  'Comprei um apartamento para alugar. Preciso entender como declarar o aluguel no IR e quais impostos pagar.',
  'Cliente já forneceu documentos do imóvel. Iniciando análise da melhor forma de tributação.',
  '{
    "property_type": "Apartamento",
    "rental_income": 2500,
    "property_value": 350000,
    "has_financing": true
  }'::jsonb,
  'SEU_STUDENT_ID_AQUI',
  NOW() - INTERVAL '2 days',
  NOW(),
  NOW() - INTERVAL '1 day',
  NOW()
);

-- Exemplo 4: Atendimento Urgente - Regularização Fiscal
INSERT INTO public.fiscal_appointments (
  protocol,
  service_type,
  service_title,
  service_category,
  client_name,
  client_email,
  client_phone,
  client_cpf,
  address_street,
  address_number,
  address_neighborhood,
  address_city,
  address_state,
  address_zipcode,
  urgency_level,
  preferred_date,
  preferred_time,
  preferred_period,
  status,
  client_notes,
  service_details,
  assigned_student_id,
  created_at,
  updated_at,
  confirmed_at
) VALUES (
  'FAP-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-004',
  'regularizacao-fiscal',
  'Regularização de CPF com pendências',
  'Regularização',
  'Pedro Henrique Souza',
  'pedro.souza@email.com',
  '(11) 95432-1098',
  '789.123.456-00',
  'Rua da Consolação',
  '456',
  'Consolação',
  'São Paulo',
  'SP',
  '01301-000',
  'URGENTE',
  CURRENT_DATE + INTERVAL '1 day',
  '08:00',
  'MANHA',
  'CONFIRMADO',
  'Meu CPF está com pendências na Receita Federal. Preciso regularizar urgentemente para conseguir um emprego.',
  '{
    "issue_type": "CPF com pendências",
    "blocking_situation": "Contratação de emprego",
    "urgency_reason": "Proposta de emprego com prazo"
  }'::jsonb,
  'SEU_STUDENT_ID_AQUI',
  NOW(),
  NOW(),
  NOW()
);

-- Exemplo 5: Atendimento Concluído - Emissão de Certidão
INSERT INTO public.fiscal_appointments (
  protocol,
  service_type,
  service_title,
  service_category,
  client_name,
  client_email,
  client_phone,
  client_cpf,
  address_street,
  address_number,
  address_neighborhood,
  address_city,
  address_state,
  address_zipcode,
  urgency_level,
  preferred_date,
  preferred_time,
  preferred_period,
  status,
  client_notes,
  internal_notes,
  service_details,
  assigned_student_id,
  created_at,
  updated_at,
  confirmed_at,
  scheduled_at,
  completed_at
) VALUES (
  'FAP-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-005',
  'emissao-certidao',
  'Emissão de Certidão Negativa de Débitos',
  'Certidões',
  'Fernanda Lima Rodrigues',
  'fernanda.lima@email.com',
  '(11) 94321-0987',
  '321.654.987-00',
  'Rua Oscar Freire',
  '321',
  'Jardins',
  'São Paulo',
  'SP',
  '01426-000',
  'BAIXA',
  CURRENT_DATE - INTERVAL '5 days',
  '15:00',
  'TARDE',
  'CONCLUIDO',
  'Preciso da certidão negativa para participar de um processo licitatório.',
  'Certidão emitida com sucesso. Cliente orientado sobre validade e uso do documento.',
  '{
    "document_type": "Certidão Negativa Federal",
    "purpose": "Licitação",
    "delivered_format": "Digital"
  }'::jsonb,
  'SEU_STUDENT_ID_AQUI',
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '6 days',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '2 days'
);

-- Verificar se os dados foram inseridos
SELECT
  protocol,
  service_title,
  client_name,
  status,
  urgency_level,
  preferred_date
FROM public.fiscal_appointments
WHERE assigned_student_id = 'SEU_STUDENT_ID_AQUI'
ORDER BY created_at DESC;
