-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  protocol character varying NOT NULL UNIQUE,
  student_id uuid,
  student_name character varying NOT NULL,
  client_name character varying NOT NULL,
  client_email character varying,
  client_phone character varying,
  client_document character varying,
  client_category character varying NOT NULL,
  service_type character varying NOT NULL,
  service_description text,
  scheduled_date date NOT NULL,
  scheduled_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  is_online boolean DEFAULT false,
  meeting_link text,
  location text,
  status character varying DEFAULT 'AGENDADO'::character varying CHECK (status::text = ANY (ARRAY['AGENDADO'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying, 'CANCELADO'::character varying, 'NAO_COMPARECEU'::character varying]::text[])),
  urgency character varying DEFAULT 'MEDIA'::character varying CHECK (urgency::text = ANY (ARRAY['BAIXA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying]::text[])),
  client_satisfaction_rating integer CHECK (client_satisfaction_rating >= 1 AND client_satisfaction_rating <= 5),
  client_feedback text,
  student_notes text,
  supervisor_validation boolean DEFAULT false,
  supervisor_id uuid,
  validated_at timestamp with time zone,
  documents jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  CONSTRAINT attendances_pkey PRIMARY KEY (id),
  CONSTRAINT attendances_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendances_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.backup_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  coordinator_id uuid NOT NULL UNIQUE,
  auto_backup_enabled boolean DEFAULT false,
  auto_backup_frequency character varying CHECK (auto_backup_frequency::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying]::text[])),
  auto_backup_time time without time zone DEFAULT '02:00:00'::time without time zone,
  default_export_format character varying DEFAULT 'csv'::character varying,
  include_feedbacks boolean DEFAULT true,
  include_student_info boolean DEFAULT true,
  include_client_info boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  notification_email character varying,
  retention_days integer DEFAULT 90,
  encryption_enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT backup_configurations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.backup_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  coordinator_id uuid NOT NULL,
  coordinator_name character varying NOT NULL,
  coordinator_email character varying NOT NULL,
  backup_type character varying NOT NULL CHECK (backup_type::text = ANY (ARRAY['download'::character varying, 'email'::character varying, 'preview'::character varying]::text[])),
  export_format character varying NOT NULL CHECK (export_format::text = ANY (ARRAY['csv'::character varying, 'json'::character varying, 'pdf'::character varying, 'excel'::character varying, 'txt'::character varying, 'docx'::character varying]::text[])),
  file_size_kb numeric,
  total_records integer NOT NULL DEFAULT 0,
  filter_applied jsonb,
  date_range jsonb,
  status_filter ARRAY,
  ip_address character varying,
  user_agent text,
  download_url text,
  email_sent_to character varying,
  success boolean DEFAULT true,
  error_message text,
  execution_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT backup_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bd_ativo (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  num bigint,
  CONSTRAINT bd_ativo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_access_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  link_token character varying NOT NULL UNIQUE,
  link_slug character varying UNIQUE,
  created_by_student_id uuid NOT NULL,
  created_by_student_name character varying NOT NULL,
  title character varying DEFAULT 'Chat NAF - Assistente Virtual'::character varying,
  description text,
  custom_message text,
  max_uses integer,
  current_uses integer DEFAULT 0,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  last_used_at timestamp with time zone,
  total_conversations_started integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_access_links_pkey PRIMARY KEY (id),
  CONSTRAINT chat_access_links_student_fkey FOREIGN KEY (created_by_student_id) REFERENCES public.students(id)
);
CREATE TABLE public.chat_appointments (
  id character varying NOT NULL,
  user_id character varying NOT NULL,
  coordinator_id character varying,
  conversation_id character varying,
  scheduled_date date NOT NULL,
  scheduled_time time without time zone NOT NULL,
  scheduled_datetime timestamp without time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  service_type character varying,
  service_description text,
  priority character varying DEFAULT 'normal'::character varying,
  status character varying DEFAULT 'scheduled'::character varying,
  notes text,
  reminder_sent boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  chat_session_id character varying,
  created_by_user_id character varying,
  created_by_user_type character varying,
  assigned_student_id character varying,
  CONSTRAINT chat_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT chat_appointments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.chat_users(id)
);
CREATE TABLE public.chat_conversation_history (
  id character varying NOT NULL,
  user_id character varying NOT NULL,
  coordinator_id character varying,
  appointment_id character varying,
  conversation_id character varying NOT NULL,
  title character varying,
  summary text,
  total_messages integer DEFAULT 0,
  started_at timestamp without time zone NOT NULL,
  ended_at timestamp without time zone,
  duration_minutes integer,
  status character varying DEFAULT 'active'::character varying,
  satisfaction_rating integer,
  satisfaction_feedback text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT chat_conversation_history_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversation_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.chat_users(id),
  CONSTRAINT chat_conversation_history_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.chat_appointments(id)
);
CREATE TABLE public.chat_conversations (
  id integer NOT NULL DEFAULT nextval('chat_conversations_id_seq'::regclass),
  user_id character varying NOT NULL,
  user_name character varying DEFAULT 'Usuário'::character varying,
  user_email character varying,
  status character varying DEFAULT 'active'::character varying,
  is_online boolean DEFAULT false,
  coordinator_id uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  human_requested boolean DEFAULT false,
  human_request_timestamp timestamp with time zone,
  chat_accepted_by uuid,
  chat_accepted_at timestamp with time zone,
  chat_ended_by character varying,
  chat_ended_at timestamp with time zone,
  coordinator_name character varying,
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES public.coordinator_users(id),
  CONSTRAINT chat_conversations_chat_accepted_by_fkey FOREIGN KEY (chat_accepted_by) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.chat_feedback (
  id integer NOT NULL DEFAULT nextval('chat_feedback_id_seq'::regclass),
  conversation_id integer,
  user_id character varying NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  coordinator_id uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT chat_feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id),
  CONSTRAINT chat_feedback_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.chat_link_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  link_id uuid NOT NULL,
  link_token character varying NOT NULL,
  user_ip character varying,
  user_agent text,
  user_id character varying,
  conversation_id integer,
  user_country character varying,
  user_city character varying,
  accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_link_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT chat_link_usage_link_fkey FOREIGN KEY (link_id) REFERENCES public.chat_access_links(id),
  CONSTRAINT chat_link_usage_conversation_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.chat_messages (
  id integer NOT NULL DEFAULT nextval('chat_messages_id_seq'::regclass),
  conversation_id integer,
  content text NOT NULL,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'coordinator'::character varying]::text[])),
  sender_id character varying,
  sender_name character varying,
  is_ai_response boolean DEFAULT false,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  session_id character varying,
  message_text text,
  message_type character varying DEFAULT 'text'::character varying,
  sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  read_at timestamp without time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.chat_persistent_messages (
  id character varying NOT NULL,
  conversation_history_id character varying NOT NULL,
  conversation_id character varying NOT NULL,
  user_id character varying,
  content text NOT NULL,
  sender_type character varying NOT NULL,
  sender_id character varying,
  sender_name character varying,
  is_ai_response boolean DEFAULT false,
  message_type character varying DEFAULT 'text'::character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT chat_persistent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_persistent_messages_conversation_history_id_fkey FOREIGN KEY (conversation_history_id) REFERENCES public.chat_conversation_history(id),
  CONSTRAINT chat_persistent_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.chat_users(id)
);
CREATE TABLE public.chat_registration_sessions (
  id character varying NOT NULL,
  conversation_id character varying NOT NULL,
  current_step integer DEFAULT 1,
  total_steps integer DEFAULT 8,
  form_data jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'in_progress'::character varying,
  started_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT chat_registration_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_sessions (
  id character varying NOT NULL,
  user_id character varying,
  user_type character varying NOT NULL CHECK (user_type::text = ANY (ARRAY['client'::character varying, 'student'::character varying, 'coordinator'::character varying]::text[])),
  user_name character varying NOT NULL,
  user_email character varying,
  user_phone character varying,
  session_token character varying NOT NULL UNIQUE,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'transferred'::character varying]::text[])),
  started_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  ended_at timestamp without time zone,
  assigned_coordinator_id character varying,
  assigned_student_id character varying,
  transferred_from_user_id character varying,
  transferred_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_transfers (
  id character varying NOT NULL,
  session_id character varying,
  from_user_id character varying NOT NULL,
  from_user_type character varying NOT NULL CHECK (from_user_type::text = ANY (ARRAY['student'::character varying, 'coordinator'::character varying]::text[])),
  from_user_name character varying NOT NULL,
  to_user_id character varying NOT NULL,
  to_user_type character varying NOT NULL CHECK (to_user_type::text = ANY (ARRAY['student'::character varying, 'coordinator'::character varying]::text[])),
  to_user_name character varying NOT NULL,
  transfer_reason text,
  transfer_notes text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'completed'::character varying]::text[])),
  transferred_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  accepted_at timestamp without time zone,
  completed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_transfers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_users (
  id character varying NOT NULL,
  conversation_id character varying,
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  cpf character varying,
  birth_date date,
  address text,
  city character varying,
  state character varying,
  occupation character varying,
  company character varying,
  income_range character varying,
  preferred_contact character varying DEFAULT 'email'::character varying,
  service_interest jsonb DEFAULT '[]'::jsonb,
  registration_source character varying DEFAULT 'chat'::character varying,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  password_hash character varying,
  assigned_coordinator_id character varying,
  assigned_student_id character varying,
  last_login timestamp without time zone,
  password character varying,
  CONSTRAINT chat_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coordinator_availability (
  id character varying NOT NULL,
  coordinator_id character varying NOT NULL,
  day_of_week integer NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  max_appointments integer DEFAULT 8,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT coordinator_availability_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coordinator_login_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  login_time timestamp with time zone DEFAULT now(),
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  failure_reason text,
  CONSTRAINT coordinator_login_logs_pkey PRIMARY KEY (id),
  CONSTRAINT coordinator_login_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.coordinator_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_type character varying NOT NULL,
  report_name character varying NOT NULL,
  generated_by uuid,
  file_path text,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT coordinator_reports_pkey PRIMARY KEY (id),
  CONSTRAINT coordinator_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.coordinator_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_used timestamp with time zone DEFAULT now(),
  CONSTRAINT coordinator_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT coordinator_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.coordinator_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coordinator_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.course_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid,
  enrollment_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  would_recommend boolean,
  difficulty_rating integer CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  content_quality integer CHECK (content_quality >= 1 AND content_quality <= 5),
  instructor_rating integer CHECK (instructor_rating >= 1 AND instructor_rating <= 5),
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT course_evaluations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_evaluations_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id)
);
CREATE TABLE public.course_themes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid,
  title character varying NOT NULL,
  description text,
  theme_order integer NOT NULL,
  estimated_duration integer DEFAULT 0,
  learning_objectives ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_themes_pkey PRIMARY KEY (id),
  CONSTRAINT course_themes_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  type character varying NOT NULL,
  cover_image text,
  difficulty_level character varying DEFAULT 'iniciante'::character varying,
  estimated_duration integer DEFAULT 0,
  is_mandatory boolean DEFAULT false,
  external_url text,
  instructor_name character varying,
  skills_learned ARRAY,
  prerequisites ARRAY,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  metric_name character varying NOT NULL,
  metric_value numeric NOT NULL,
  metric_date date NOT NULL,
  category character varying,
  subcategory character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fiscal_appointment_feedbacks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL,
  client_name character varying NOT NULL,
  client_email character varying NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  service_quality integer CHECK (service_quality >= 1 AND service_quality <= 5),
  student_attention integer CHECK (student_attention >= 1 AND student_attention <= 5),
  problem_resolution integer CHECK (problem_resolution >= 1 AND problem_resolution <= 5),
  would_recommend boolean DEFAULT true,
  additional_comments text,
  created_at timestamp with time zone DEFAULT now(),
  student_id uuid,
  attendance_quality integer CHECK (attendance_quality >= 1 AND attendance_quality <= 5),
  punctuality integer CHECK (punctuality >= 1 AND punctuality <= 5),
  professionalism integer CHECK (professionalism >= 1 AND professionalism <= 5),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fiscal_appointment_feedbacks_pkey PRIMARY KEY (id),
  CONSTRAINT fiscal_appointment_feedbacks_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.fiscal_appointments(id),
  CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.fiscal_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_type character varying NOT NULL,
  service_title character varying NOT NULL,
  service_category character varying NOT NULL,
  client_name character varying NOT NULL,
  client_email character varying NOT NULL,
  client_phone character varying NOT NULL,
  client_cpf character varying,
  client_birth_date date,
  address_street character varying,
  address_number character varying,
  address_complement character varying,
  address_neighborhood character varying,
  address_city character varying NOT NULL,
  address_state character varying NOT NULL,
  address_zipcode character varying,
  service_details jsonb,
  urgency_level character varying DEFAULT 'NORMAL'::character varying CHECK (urgency_level::text = ANY (ARRAY['BAIXA'::character varying, 'NORMAL'::character varying, 'ALTA'::character varying, 'URGENTE'::character varying]::text[])),
  preferred_date date,
  preferred_time time without time zone,
  preferred_period character varying CHECK (preferred_period::text = ANY (ARRAY['MANHA'::character varying, 'TARDE'::character varying, 'NOITE'::character varying]::text[])),
  status character varying DEFAULT 'PENDENTE'::character varying CHECK (status::text = ANY (ARRAY['PENDENTE'::character varying, 'CONFIRMADO'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying, 'CANCELADO'::character varying]::text[])),
  protocol character varying UNIQUE,
  assigned_student_id uuid,
  assigned_coordinator_id uuid,
  client_notes text,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  scheduled_at timestamp with time zone,
  completed_at timestamp with time zone,
  assigned_student_email character varying,
  client_satisfaction_rating integer CHECK (client_satisfaction_rating >= 1 AND client_satisfaction_rating <= 5),
  CONSTRAINT fiscal_appointments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fiscal_service_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_type character varying NOT NULL UNIQUE,
  service_title character varying NOT NULL,
  service_category character varying NOT NULL,
  required_fields jsonb,
  optional_fields jsonb,
  required_documents jsonb,
  estimated_duration_minutes integer DEFAULT 60,
  complexity_level character varying DEFAULT 'MEDIO'::character varying,
  description text,
  steps jsonb,
  important_notes jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fiscal_service_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.module_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid,
  title character varying NOT NULL,
  description text,
  question_type character varying NOT NULL,
  question_data jsonb NOT NULL,
  correct_answer jsonb,
  explanation text,
  points integer DEFAULT 10,
  difficulty character varying DEFAULT 'easy'::character varying,
  exercise_order integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT module_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT module_exercises_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.theme_modules(id)
);
CREATE TABLE public.naf_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text NOT NULL,
  detailed_description text,
  category USER-DEFINED NOT NULL,
  subcategory character varying,
  difficulty USER-DEFINED DEFAULT 'basico'::service_difficulty,
  status USER-DEFINED DEFAULT 'ativo'::service_status,
  is_featured boolean DEFAULT false,
  is_popular boolean DEFAULT false,
  priority_order integer DEFAULT 0,
  estimated_duration_minutes integer,
  required_documents ARRAY,
  prerequisites ARRAY,
  icon_name character varying,
  color_scheme character varying DEFAULT 'blue'::character varying,
  banner_image_url text,
  contact_info jsonb,
  process_steps jsonb,
  meta_title character varying,
  meta_description text,
  keywords ARRAY,
  views_count integer DEFAULT 0,
  requests_count integer DEFAULT 0,
  satisfaction_rating numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT naf_services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_delivery_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid,
  delivery_method character varying NOT NULL,
  delivery_status character varying NOT NULL,
  provider character varying,
  external_id character varying,
  error_message text,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_delivery_log_pkey PRIMARY KEY (id),
  CONSTRAINT notification_delivery_log_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_type USER-DEFINED NOT NULL,
  notification_type USER-DEFINED NOT NULL,
  email_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  timezone character varying DEFAULT 'America/Sao_Paulo'::character varying,
  digest_frequency character varying DEFAULT 'immediate'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_name character varying NOT NULL UNIQUE,
  notification_type USER-DEFINED NOT NULL,
  user_type USER-DEFINED NOT NULL,
  title_template text NOT NULL,
  message_template text NOT NULL,
  default_priority USER-DEFINED DEFAULT 'medium'::priority_enum,
  default_icon character varying,
  default_color character varying,
  default_send_email boolean DEFAULT false,
  default_send_push boolean DEFAULT true,
  default_send_sms boolean DEFAULT false,
  default_expires_hours integer,
  is_persistent boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  recipient_type USER-DEFINED NOT NULL,
  recipient_email character varying CHECK (recipient_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  title character varying NOT NULL,
  message text NOT NULL,
  notification_type USER-DEFINED NOT NULL,
  priority USER-DEFINED DEFAULT 'medium'::priority_enum,
  metadata jsonb DEFAULT '{}'::jsonb,
  icon character varying,
  color character varying,
  action_url text,
  action_label character varying,
  send_email boolean DEFAULT false,
  send_push boolean DEFAULT false,
  send_sms boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'unread'::notification_status_enum,
  is_persistent boolean DEFAULT false,
  expires_at timestamp with time zone,
  related_appointment_id uuid,
  related_training_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  archived_at timestamp with time zone,
  sent_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.report_history (
  id text NOT NULL,
  student_id text NOT NULL,
  student_name text NOT NULL,
  student_email text NOT NULL,
  report_type text NOT NULL,
  template text NOT NULL,
  format text NOT NULL,
  custom_template jsonb,
  stats jsonb NOT NULL,
  total_attendances integer NOT NULL DEFAULT 0,
  completed_attendances integer NOT NULL DEFAULT 0,
  total_trainings integer NOT NULL DEFAULT 0,
  completed_trainings integer NOT NULL DEFAULT 0,
  success_rate double precision NOT NULL DEFAULT 0,
  avg_rating double precision NOT NULL DEFAULT 0,
  generated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_size integer,
  CONSTRAINT report_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_name character varying NOT NULL,
  requests_count integer DEFAULT 0,
  completed_count integer DEFAULT 0,
  pending_count integer DEFAULT 0,
  avg_duration_minutes integer DEFAULT 0,
  satisfaction_rating numeric DEFAULT 0.00,
  metric_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  activity_type character varying NOT NULL,
  activity_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT student_activity_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_availability_pkey PRIMARY KEY (id),
  CONSTRAINT student_availability_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid,
  enrollment_id uuid,
  certificate_code character varying NOT NULL UNIQUE,
  issued_at timestamp with time zone DEFAULT now(),
  final_score numeric,
  total_time_spent integer,
  certificate_url text,
  is_valid boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT student_certificates_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT student_certificates_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id)
);
CREATE TABLE public.student_course_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid,
  enrollment_date timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  current_theme_id uuid,
  current_module_id uuid,
  overall_progress numeric DEFAULT 0.00,
  total_time_spent integer DEFAULT 0,
  status character varying DEFAULT 'enrolled'::character varying,
  certificate_issued boolean DEFAULT false,
  final_grade numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  enrollment_notes text,
  CONSTRAINT student_course_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT student_course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT student_course_enrollments_current_theme_id_fkey FOREIGN KEY (current_theme_id) REFERENCES public.course_themes(id),
  CONSTRAINT student_course_enrollments_current_module_id_fkey FOREIGN KEY (current_module_id) REFERENCES public.theme_modules(id)
);
CREATE TABLE public.student_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  evaluator_id uuid,
  attendance_id uuid,
  technical_score integer CHECK (technical_score >= 1 AND technical_score <= 5),
  communication_score integer CHECK (communication_score >= 1 AND communication_score <= 5),
  punctuality_score integer CHECK (punctuality_score >= 1 AND punctuality_score <= 5),
  professionalism_score integer CHECK (professionalism_score >= 1 AND professionalism_score <= 5),
  overall_score numeric,
  feedback text,
  improvement_areas ARRAY,
  strengths ARRAY,
  evaluation_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT student_evaluations_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_evaluations_evaluator_id_fkey FOREIGN KEY (evaluator_id) REFERENCES public.coordinator_users(id),
  CONSTRAINT student_evaluations_attendance_id_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendances(id)
);
CREATE TABLE public.student_exercise_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  exercise_id uuid,
  module_progress_id uuid,
  answer_data jsonb NOT NULL,
  is_correct boolean,
  points_earned integer DEFAULT 0,
  attempt_number integer DEFAULT 1,
  time_taken integer,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_exercise_answers_pkey PRIMARY KEY (id),
  CONSTRAINT student_exercise_answers_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.module_exercises(id),
  CONSTRAINT student_exercise_answers_module_progress_id_fkey FOREIGN KEY (module_progress_id) REFERENCES public.student_module_progress(id)
);
CREATE TABLE public.student_module_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  module_id uuid,
  theme_progress_id uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  time_spent integer DEFAULT 0,
  status character varying DEFAULT 'not_started'::character varying,
  notes text,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_module_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_module_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.theme_modules(id),
  CONSTRAINT student_module_progress_theme_progress_id_fkey FOREIGN KEY (theme_progress_id) REFERENCES public.student_theme_progress(id)
);
CREATE TABLE public.student_module_progress_v2 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  module_id uuid,
  enrollment_id uuid,
  theme_progress_id uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  time_spent integer DEFAULT 0,
  status character varying DEFAULT 'not_started'::character varying,
  completion_percentage numeric DEFAULT 0.00,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_module_progress_v2_pkey PRIMARY KEY (id),
  CONSTRAINT student_module_progress_v2_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.theme_modules(id),
  CONSTRAINT student_module_progress_v2_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id),
  CONSTRAINT student_module_progress_v2_theme_progress_id_fkey FOREIGN KEY (theme_progress_id) REFERENCES public.student_theme_progress(id)
);
CREATE TABLE public.student_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_name character varying NOT NULL,
  course character varying,
  total_attendances integer DEFAULT 0,
  avg_rating numeric DEFAULT 0.00,
  last_activity timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_performance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_progress_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  enrollment_id uuid,
  course_id uuid,
  current_theme_id uuid,
  current_module_id uuid,
  last_activity_at timestamp with time zone DEFAULT now(),
  total_modules_completed integer DEFAULT 0,
  total_modules_in_course integer DEFAULT 0,
  current_streak_days integer DEFAULT 0,
  last_streak_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_progress_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT student_progress_tracking_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id),
  CONSTRAINT student_progress_tracking_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT student_progress_tracking_current_theme_id_fkey FOREIGN KEY (current_theme_id) REFERENCES public.course_themes(id),
  CONSTRAINT student_progress_tracking_current_module_id_fkey FOREIGN KEY (current_module_id) REFERENCES public.theme_modules(id)
);
CREATE TABLE public.student_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_used timestamp with time zone DEFAULT now(),
  CONSTRAINT student_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT student_sessions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_theme_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  theme_id uuid,
  enrollment_id uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  progress numeric DEFAULT 0.00,
  time_spent integer DEFAULT 0,
  status character varying DEFAULT 'not_started'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_theme_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_theme_progress_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.course_themes(id),
  CONSTRAINT student_theme_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id)
);
CREATE TABLE public.student_training_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  training_id uuid,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  score integer CHECK (score >= 0 AND score <= 100),
  attempts integer DEFAULT 1,
  time_spent_minutes integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  notes text,
  CONSTRAINT student_training_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_training_progress_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_training_progress_training_id_fkey FOREIGN KEY (training_id) REFERENCES public.trainings(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  name character varying NOT NULL,
  phone character varying,
  document character varying UNIQUE,
  course character varying NOT NULL,
  semester character varying NOT NULL,
  university character varying DEFAULT 'Estácio'::character varying,
  registration_number character varying UNIQUE,
  birth_date date,
  address jsonb,
  emergency_contact jsonb,
  specializations ARRAY,
  available_hours ARRAY,
  status character varying DEFAULT 'ATIVO'::character varying CHECK (status::text = ANY (ARRAY['ATIVO'::character varying, 'INATIVO'::character varying, 'TREINAMENTO'::character varying, 'SUSPENSO'::character varying]::text[])),
  profile_picture_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  registration_year integer,
  registration_semester integer,
  CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE TABLE public.theme_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  theme_id uuid,
  title character varying NOT NULL,
  description text,
  content jsonb NOT NULL,
  module_order integer NOT NULL,
  module_type character varying DEFAULT 'lesson'::character varying,
  estimated_duration integer DEFAULT 0,
  video_url text,
  resources jsonb,
  learning_objectives ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT theme_modules_pkey PRIMARY KEY (id),
  CONSTRAINT theme_modules_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.course_themes(id)
);
CREATE TABLE public.trainings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  content text,
  duration_minutes integer NOT NULL,
  difficulty character varying DEFAULT 'BÁSICO'::character varying CHECK (difficulty::text = ANY (ARRAY['BÁSICO'::character varying, 'INTERMEDIÁRIO'::character varying, 'AVANÇADO'::character varying]::text[])),
  topics ARRAY NOT NULL,
  learning_objectives ARRAY,
  prerequisites ARRAY,
  resources jsonb,
  instructor_name character varying,
  is_mandatory boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trainings_pkey PRIMARY KEY (id)
);