-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  protocol character varying NOT NULL UNIQUE,
  student_id uuid,
  student_name character varying NOT NULL,
  client_name character varying NOT NULL,
  client_email character varying,
  client_phone character varying,
  client_document character varying,
  client_category character varying NOT NULL,
  service_type character varying NOT NULL,
  service_description text,
  scheduled_date date NOT NULL,
  scheduled_time time without time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  is_online boolean DEFAULT false,
  meeting_link text,
  location text,
  status character varying DEFAULT 'AGENDADO'::character varying CHECK (status::text = ANY (ARRAY['AGENDADO'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying, 'CANCELADO'::character varying, 'NAO_COMPARECEU'::character varying]::text[])),
  urgency character varying DEFAULT 'MEDIA'::character varying CHECK (urgency::text = ANY (ARRAY['BAIXA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying]::text[])),
  client_satisfaction_rating integer CHECK (client_satisfaction_rating >= 1 AND client_satisfaction_rating <= 5),
  client_feedback text,
  student_notes text,
  supervisor_validation boolean DEFAULT false,
  supervisor_id uuid,
  validated_at timestamp with time zone,
  documents jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  CONSTRAINT attendances_pkey PRIMARY KEY (id),
  CONSTRAINT attendances_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendances_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.chat_conversations (
  id integer NOT NULL DEFAULT nextval('chat_conversations_id_seq'::regclass),
  user_id character varying NOT NULL,
  user_name character varying DEFAULT 'Usuário'::character varying,
  user_email character varying,
  status character varying DEFAULT 'active'::character varying,
  is_online boolean DEFAULT false,
  coordinator_id uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  human_requested boolean DEFAULT false,
  human_request_timestamp timestamp with time zone,
  chat_accepted_by uuid,
  chat_accepted_at timestamp with time zone,
  chat_ended_by character varying,
  chat_ended_at timestamp with time zone,
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES public.coordinator_users(id),
  CONSTRAINT chat_conversations_chat_accepted_by_fkey FOREIGN KEY (chat_accepted_by) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.chat_feedback (
  id integer NOT NULL DEFAULT nextval('chat_feedback_id_seq'::regclass),
  conversation_id integer,
  user_id character varying NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  coordinator_id uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT chat_feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id),
  CONSTRAINT chat_feedback_coordinator_id_fkey FOREIGN KEY (coordinator_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.chat_messages (
  id integer NOT NULL DEFAULT nextval('chat_messages_id_seq'::regclass),
  conversation_id integer,
  content text NOT NULL,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'coordinator'::character varying]::text[])),
  sender_id character varying,
  sender_name character varying,
  is_ai_response boolean DEFAULT false,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.coordinator_login_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  login_time timestamp with time zone DEFAULT now(),
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  failure_reason text,
  CONSTRAINT coordinator_login_logs_pkey PRIMARY KEY (id),
  CONSTRAINT coordinator_login_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.coordinator_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_type character varying NOT NULL,
  report_name character varying NOT NULL,
  generated_by uuid,
  file_path text,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT coordinator_reports_pkey PRIMARY KEY (id),
  CONSTRAINT coordinator_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.coordinator_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_used timestamp with time zone DEFAULT now(),
  CONSTRAINT coordinator_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT coordinator_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.coordinator_users(id)
);
CREATE TABLE public.coordinator_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coordinator_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.course_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid,
  enrollment_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  would_recommend boolean,
  difficulty_rating integer CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  content_quality integer CHECK (content_quality >= 1 AND content_quality <= 5),
  instructor_rating integer CHECK (instructor_rating >= 1 AND instructor_rating <= 5),
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT course_evaluations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_evaluations_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id)
);
CREATE TABLE public.course_themes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid,
  title character varying NOT NULL,
  description text,
  theme_order integer NOT NULL,
  estimated_duration integer DEFAULT 0,
  learning_objectives ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_themes_pkey PRIMARY KEY (id),
  CONSTRAINT course_themes_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  type character varying NOT NULL,
  cover_image text,
  difficulty_level character varying DEFAULT 'iniciante'::character varying,
  estimated_duration integer DEFAULT 0,
  is_mandatory boolean DEFAULT false,
  external_url text,
  instructor_name character varying,
  skills_learned ARRAY,
  prerequisites ARRAY,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  metric_name character varying NOT NULL,
  metric_value numeric NOT NULL,
  metric_date date NOT NULL,
  category character varying,
  subcategory character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fiscal_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_type character varying NOT NULL,
  service_title character varying NOT NULL,
  service_category character varying NOT NULL,
  client_name character varying NOT NULL,
  client_email character varying NOT NULL,
  client_phone character varying NOT NULL,
  client_cpf character varying,
  client_birth_date date,
  address_street character varying,
  address_number character varying,
  address_complement character varying,
  address_neighborhood character varying,
  address_city character varying NOT NULL,
  address_state character varying NOT NULL,
  address_zipcode character varying,
  service_details jsonb,
  urgency_level character varying DEFAULT 'NORMAL'::character varying CHECK (urgency_level::text = ANY (ARRAY['BAIXA'::character varying, 'NORMAL'::character varying, 'ALTA'::character varying, 'URGENTE'::character varying]::text[])),
  preferred_date date,
  preferred_time time without time zone,
  preferred_period character varying CHECK (preferred_period::text = ANY (ARRAY['MANHA'::character varying, 'TARDE'::character varying, 'NOITE'::character varying]::text[])),
  status character varying DEFAULT 'PENDENTE'::character varying CHECK (status::text = ANY (ARRAY['PENDENTE'::character varying, 'CONFIRMADO'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying, 'CANCELADO'::character varying]::text[])),
  protocol character varying UNIQUE,
  assigned_student_id uuid,
  assigned_coordinator_id uuid,
  client_notes text,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  scheduled_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT fiscal_appointments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fiscal_service_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_type character varying NOT NULL UNIQUE,
  service_title character varying NOT NULL,
  service_category character varying NOT NULL,
  required_fields jsonb,
  optional_fields jsonb,
  required_documents jsonb,
  estimated_duration_minutes integer DEFAULT 60,
  complexity_level character varying DEFAULT 'MEDIO'::character varying,
  description text,
  steps jsonb,
  important_notes jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fiscal_service_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.module_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid,
  title character varying NOT NULL,
  description text,
  question_type character varying NOT NULL,
  question_data jsonb NOT NULL,
  correct_answer jsonb,
  explanation text,
  points integer DEFAULT 10,
  difficulty character varying DEFAULT 'easy'::character varying,
  exercise_order integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT module_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT module_exercises_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.theme_modules(id)
);
CREATE TABLE public.naf_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text NOT NULL,
  detailed_description text,
  category USER-DEFINED NOT NULL,
  subcategory character varying,
  difficulty USER-DEFINED DEFAULT 'basico'::service_difficulty,
  status USER-DEFINED DEFAULT 'ativo'::service_status,
  is_featured boolean DEFAULT false,
  is_popular boolean DEFAULT false,
  priority_order integer DEFAULT 0,
  estimated_duration_minutes integer,
  required_documents ARRAY,
  prerequisites ARRAY,
  icon_name character varying,
  color_scheme character varying DEFAULT 'blue'::character varying,
  banner_image_url text,
  contact_info jsonb,
  process_steps jsonb,
  meta_title character varying,
  meta_description text,
  keywords ARRAY,
  views_count integer DEFAULT 0,
  requests_count integer DEFAULT 0,
  satisfaction_rating numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT naf_services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_delivery_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid,
  delivery_method character varying NOT NULL,
  delivery_status character varying NOT NULL,
  provider character varying,
  external_id character varying,
  error_message text,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_delivery_log_pkey PRIMARY KEY (id),
  CONSTRAINT notification_delivery_log_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_type USER-DEFINED NOT NULL,
  notification_type USER-DEFINED NOT NULL,
  email_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  timezone character varying DEFAULT 'America/Sao_Paulo'::character varying,
  digest_frequency character varying DEFAULT 'immediate'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_name character varying NOT NULL UNIQUE,
  notification_type USER-DEFINED NOT NULL,
  user_type USER-DEFINED NOT NULL,
  title_template text NOT NULL,
  message_template text NOT NULL,
  default_priority USER-DEFINED DEFAULT 'medium'::priority_enum,
  default_icon character varying,
  default_color character varying,
  default_send_email boolean DEFAULT false,
  default_send_push boolean DEFAULT true,
  default_send_sms boolean DEFAULT false,
  default_expires_hours integer,
  is_persistent boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  recipient_type USER-DEFINED NOT NULL,
  recipient_email character varying CHECK (recipient_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  title character varying NOT NULL,
  message text NOT NULL,
  notification_type USER-DEFINED NOT NULL,
  priority USER-DEFINED DEFAULT 'medium'::priority_enum,
  metadata jsonb DEFAULT '{}'::jsonb,
  icon character varying,
  color character varying,
  action_url text,
  action_label character varying,
  send_email boolean DEFAULT false,
  send_push boolean DEFAULT false,
  send_sms boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'unread'::notification_status_enum,
  is_persistent boolean DEFAULT false,
  expires_at timestamp with time zone,
  related_appointment_id uuid,
  related_training_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  archived_at timestamp with time zone,
  sent_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_name character varying NOT NULL,
  requests_count integer DEFAULT 0,
  completed_count integer DEFAULT 0,
  pending_count integer DEFAULT 0,
  avg_duration_minutes integer DEFAULT 0,
  satisfaction_rating numeric DEFAULT 0.00,
  metric_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  activity_type character varying NOT NULL,
  activity_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT student_activity_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_availability_pkey PRIMARY KEY (id),
  CONSTRAINT student_availability_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid,
  enrollment_id uuid,
  certificate_code character varying NOT NULL UNIQUE,
  issued_at timestamp with time zone DEFAULT now(),
  final_score numeric,
  total_time_spent integer,
  certificate_url text,
  is_valid boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT student_certificates_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT student_certificates_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id)
);
CREATE TABLE public.student_course_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid,
  enrollment_date timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  current_theme_id uuid,
  current_module_id uuid,
  overall_progress numeric DEFAULT 0.00,
  total_time_spent integer DEFAULT 0,
  status character varying DEFAULT 'enrolled'::character varying,
  certificate_issued boolean DEFAULT false,
  final_grade numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_course_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT student_course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT student_course_enrollments_current_theme_id_fkey FOREIGN KEY (current_theme_id) REFERENCES public.course_themes(id),
  CONSTRAINT student_course_enrollments_current_module_id_fkey FOREIGN KEY (current_module_id) REFERENCES public.theme_modules(id)
);
CREATE TABLE public.student_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  evaluator_id uuid,
  attendance_id uuid,
  technical_score integer CHECK (technical_score >= 1 AND technical_score <= 5),
  communication_score integer CHECK (communication_score >= 1 AND communication_score <= 5),
  punctuality_score integer CHECK (punctuality_score >= 1 AND punctuality_score <= 5),
  professionalism_score integer CHECK (professionalism_score >= 1 AND professionalism_score <= 5),
  overall_score numeric,
  feedback text,
  improvement_areas ARRAY,
  strengths ARRAY,
  evaluation_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT student_evaluations_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_evaluations_evaluator_id_fkey FOREIGN KEY (evaluator_id) REFERENCES public.coordinator_users(id),
  CONSTRAINT student_evaluations_attendance_id_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendances(id)
);
CREATE TABLE public.student_exercise_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  exercise_id uuid,
  module_progress_id uuid,
  answer_data jsonb NOT NULL,
  is_correct boolean,
  points_earned integer DEFAULT 0,
  attempt_number integer DEFAULT 1,
  time_taken integer,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_exercise_answers_pkey PRIMARY KEY (id),
  CONSTRAINT student_exercise_answers_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.module_exercises(id),
  CONSTRAINT student_exercise_answers_module_progress_id_fkey FOREIGN KEY (module_progress_id) REFERENCES public.student_module_progress(id)
);
CREATE TABLE public.student_module_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  module_id uuid,
  theme_progress_id uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  time_spent integer DEFAULT 0,
  status character varying DEFAULT 'not_started'::character varying,
  notes text,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_module_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_module_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.theme_modules(id),
  CONSTRAINT student_module_progress_theme_progress_id_fkey FOREIGN KEY (theme_progress_id) REFERENCES public.student_theme_progress(id)
);
CREATE TABLE public.student_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_name character varying NOT NULL,
  course character varying,
  total_attendances integer DEFAULT 0,
  avg_rating numeric DEFAULT 0.00,
  last_activity timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_performance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_used timestamp with time zone DEFAULT now(),
  CONSTRAINT student_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT student_sessions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_theme_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  theme_id uuid,
  enrollment_id uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  progress numeric DEFAULT 0.00,
  time_spent integer DEFAULT 0,
  status character varying DEFAULT 'not_started'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_theme_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_theme_progress_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.course_themes(id),
  CONSTRAINT student_theme_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.student_course_enrollments(id)
);
CREATE TABLE public.student_training_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  training_id uuid,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  score integer CHECK (score >= 0 AND score <= 100),
  attempts integer DEFAULT 1,
  time_spent_minutes integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  notes text,
  CONSTRAINT student_training_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_training_progress_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_training_progress_training_id_fkey FOREIGN KEY (training_id) REFERENCES public.trainings(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  name character varying NOT NULL,
  phone character varying,
  document character varying UNIQUE,
  course character varying NOT NULL,
  semester character varying NOT NULL,
  university character varying DEFAULT 'Estácio'::character varying,
  registration_number character varying UNIQUE,
  birth_date date,
  address jsonb,
  emergency_contact jsonb,
  specializations ARRAY,
  available_hours ARRAY,
  status character varying DEFAULT 'ATIVO'::character varying CHECK (status::text = ANY (ARRAY['ATIVO'::character varying, 'INATIVO'::character varying, 'TREINAMENTO'::character varying, 'SUSPENSO'::character varying]::text[])),
  profile_picture_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE TABLE public.theme_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  theme_id uuid,
  title character varying NOT NULL,
  description text,
  content jsonb NOT NULL,
  module_order integer NOT NULL,
  module_type character varying DEFAULT 'lesson'::character varying,
  estimated_duration integer DEFAULT 0,
  video_url text,
  resources jsonb,
  learning_objectives ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT theme_modules_pkey PRIMARY KEY (id),
  CONSTRAINT theme_modules_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.course_themes(id)
);
CREATE TABLE public.trainings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  content text,
  duration_minutes integer NOT NULL,
  difficulty character varying DEFAULT 'BÁSICO'::character varying CHECK (difficulty::text = ANY (ARRAY['BÁSICO'::character varying, 'INTERMEDIÁRIO'::character varying, 'AVANÇADO'::character varying]::text[])),
  topics ARRAY NOT NULL,
  learning_objectives ARRAY,
  prerequisites ARRAY,
  resources jsonb,
  instructor_name character varying,
  is_mandatory boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trainings_pkey PRIMARY KEY (id)
);